apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: OIDC_ISSUER_URI
          value: {{ .Values.oids.issuerUri }}
        - name: OIDC_JWKS_URI
          value: {{ .Values.oids.jwksUri }}
