server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          service-a-client:
            client-id: service-a
            client-secret: ${SERVICE_A_CLIENT_SECRET:}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/master/protocol/openid-connect/token}

serviceb:
  base-url: ${SERVICE_B_BASE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
